# -*- coding: utf-8 -*-
"""Spotify

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YzsSy2pYhEqWSwK1Fr-451hfNjYKECoY
"""

url_base = 'https://api.spotify.com/v1'

ep_artist = '/artist/{artist_id}'

id_im = '6mdiAmATAx73kdxrNrnlao'

url_base+ep_artist.format(artist_id=id_im)

import requests

r = requests.get(url_base+ep_artist.format(artist_id=id_im))

r.status_code

r.json()

token_url = 'https://accounts.spotify.com/api/token'

params = {'grant_type': 'client_credentials'}

#https://developer.spotify.com/dashboard/aplications

#https://www.base64encode.org/

headers={'Authorization': 'basic ZGE0ODY2MDNkMjM4NDczN2EwZmUxNWNjMDZmMzlhZjU6N2M4NWU1MGJlNGY3NDdiMDk5NjIyOGRmYjM3OWIyYWQ='}

r = requests.post(token_url, data=params, headers=headers)

r.status_code

r.json()

token = r.json()['access_token']

header = {'Authorization': 'Bearer {}'.format(token)}

r = requests.get(url_base+ep_artist.format(artist_id=id_im), headers=headers)

r.status_code

url_busqueda = 'https://api.spotify.com/v1/search'

search_params = {'q': "BTS", 'type' : 'artist', 'market': 'BO'}

busqueda = requests.get(url_busqueda, headers=header, params=search_params)

busqueda.status_code

busqueda.json()

import pandas as pd

df = pd.DataFrame(busqueda.json()['artists']['items'])
df.head()

df.sort_values(by='popularity',ascending=False).iloc[0]['id']